### PR TITLE
deps: unpin jax/jaxlib now that numpyro 0.21.0 ships fix

### PR DESCRIPTION
**Pull request by conorheins**
## Summary
- Reverts the temporary `<0.10` cap on `jax`/`jaxlib` (and `jax[cuda12]`) introduced in #391 across `pyproject.toml` and `setup.cfg`.
- Removes the inline TODO comments referencing [pyro-ppl/numpyro#2173](https://github.com/pyro-ppl/numpyro/pull/2173).
- numpyro#2173 merged 2026-05-02 and shipped in numpyro **0.21.0** the same day. The fix wraps the `xla_pmap_p` import in a try/except so the absence on jax ≥ 0.10.0 no longer breaks `import numpyro` (and therefore `pybefit`).

## Verification
- [x] Confirmed numpyro 0.21.0 release tag contains the try/except guard in `numpyro/ops/provenance.py`.
- [x] `uv lock --dry-run` resolves cleanly: jax 0.10.0, jaxlib 0.10.0, numpyro 0.21.0, pybefit 0.1.23.
- [x] Standard `Test` CI passes on this PR.
- [x] Manual Branch Nightly run on this branch passes.

## Notes
This closes out the workaround from #389. Should be a clean inverse of #391.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by conorheins** [comment]
First nightly run ([25428706834](https://github.com/infer-actively/pymdp/actions/runs/25428706834)) green on the steps that gate this PR — `Install dependencies` and `Run nightly-marked tests` both pass on jax 0.10.0 + numpyro 0.21.0, confirming the unpin's primary goal.

It surfaced one secondary regression in `examples/advanced/pymdp_with_neural_encoder.ipynb`: 5 `jnp.clip(..., a_min=…)` calls that fell off jax 0.10's deprecation cliff (`TypeError: clip() got an unexpected keyword argument 'a_min'`). All 6 reported notebook "failures" were that single root cause cascading through later cells (`NameError` on variables that were never assigned because the prior cell crashed). Library code is unaffected — `grep` for `a_min=`/`a_max=` across `pymdp/` is clean, only the one notebook used the deprecated kwarg.

Fixed in 225c9a1 by switching to numpy-2.0-style `min=`.  Nightly passes again with this fix
